// Sample Job Data - 20+ Jobs with real company names
const jobsData = [
    {
        id: 1,
        title: "Senior Software Engineer",
        company: "TCS",
        logo: "Pictures/TCS.png",
        location: "Bangalore, India",
        salary: "₹18-25 LPA",
        experience: "3-6",
        jobType: "Full-time",
        companyType: "MNC",
        industry: "Software",
        postedDays: 1,
        description: "Looking for experienced software engineers to build scalable enterprise applications using Java, Spring Boot, and cloud technologies.",
        badges: ["Fast Hiring"],
        skills: ["Java", "Spring Boot", "AWS", "Microservices"]
    },
    {
        id: 2,
        title: "Frontend Developer",
        company: "Flipkart",
        logo: "Pictures/flipkart-logo-png_seeklogo-318406.png",
        location: "Bangalore, India",
        salary: "₹15-22 LPA",
        experience: "1-3",
        jobType: "Full-time",
        companyType: "Product",
        industry: "Software",
        postedDays: 2,
        description: "Join our dynamic frontend team to create beautiful, responsive user interfaces for millions of customers.",
        badges: ["Remote"],
        skills: ["React", "JavaScript", "TypeScript", "CSS"]
    },
    {
        id: 3,
        title: "Data Scientist",
        company: "Amazon",
        logo: "Pictures/amazon-logo-png_seeklogo-286206.png",
        location: "Hyderabad, India",
        salary: "₹25-40 LPA",
        experience: "3-6",
        jobType: "Full-time",
        companyType: "Fortune 500",
        industry: "Software",
        postedDays: 3,
        description: "Work on cutting-edge ML models to improve customer experience and optimize logistics operations.",
        badges: [],
        skills: ["Python", "Machine Learning", "SQL", "TensorFlow"]
    },
    {
        id: 4,
        title: "Product Manager",
        company: "Google",
        logo: "Pictures/GOOGLE.webp",
        location: "Bangalore, India",
        salary: "₹35-55 LPA",
        experience: "6-10",
        jobType: "Full-time",
        companyType: "Fortune 500",
        industry: "Software",
        postedDays: 1,
        description: "Lead product strategy and roadmap for Google Cloud Platform services in the APAC region.",
        badges: ["Fast Hiring"],
        skills: ["Product Strategy", "Agile", "Data Analysis", "Leadership"]
    },
    {
        id: 5,
        title: "DevOps Engineer",
        company: "Infosys",
        logo: "Pictures/INFOSYS.jpg",
        location: "Pune, India",
        salary: "₹12-18 LPA",
        experience: "1-3",
        jobType: "Full-time",
        companyType: "MNC",
        industry: "Software",
        postedDays: 5,
        description: "Automate CI/CD pipelines and manage cloud infrastructure for enterprise clients.",
        badges: [],
        skills: ["Docker", "Kubernetes", "Jenkins", "AWS"]
    },
    {
        id: 6,
        title: "UI/UX Designer",
        company: "Zomato",
        logo: "Pictures/zomato-logo-png_seeklogo-354338.png",
        location: "Gurugram, India",
        salary: "₹14-20 LPA",
        experience: "1-3",
        jobType: "Full-time",
        companyType: "Startup",
        industry: "Creative",
        postedDays: 2,
        description: "Design intuitive food ordering experiences for millions of hungry customers across India.",
        badges: ["Remote"],
        skills: ["Figma", "Adobe XD", "User Research", "Prototyping"]
    },
    {
        id: 7,
        title: "Business Analyst",
        company: "Accenture",
        logo: "Pictures/accenture-logo-png_seeklogo-369971.png",
        location: "Mumbai, India",
        salary: "₹10-16 LPA",
        experience: "1-3",
        jobType: "Full-time",
        companyType: "MNC",
        industry: "Project Management",
        postedDays: 7,
        description: "Analyze business requirements and work with stakeholders to deliver digital transformation projects.",
        badges: [],
        skills: ["SQL", "Excel", "Tableau", "JIRA"]
    },
    {
        id: 8,
        title: "Software Developer Intern",
        company: "Microsoft",
        logo: "Pictures/MICORSOFT.png",
        location: "Hyderabad, India",
        salary: "₹60-80K/month",
        experience: "0-1",
        jobType: "Internship",
        companyType: "Fortune 500",
        industry: "Software",
        postedDays: 1,
        description: "6-month internship opportunity to work on Azure cloud services with mentorship from senior engineers.",
        badges: ["Fresher", "Fast Hiring"],
        skills: ["C#", ".NET", "Azure", "Git"]
    },
    {
        id: 9,
        title: "Backend Developer",
        company: "Swiggy",
        logo: "Pictures/swiggy-logo-png_seeklogo-348257.png",
        location: "Bangalore, India",
        salary: "₹18-28 LPA",
        experience: "3-6",
        jobType: "Full-time",
        companyType: "Startup",
        industry: "Software",
        postedDays: 4,
        description: "Build high-performance backend systems handling millions of food orders daily.",
        badges: [],
        skills: ["Node.js", "Go", "MongoDB", "Redis"]
    },
    {
        id: 10,
        title: "Cloud Architect",
        company: "IBM",
        logo: "Pictures/IBM.png",
        location: "Bangalore, India",
        salary: "₹30-45 LPA",
        experience: "6-10",
        jobType: "Full-time",
        companyType: "MNC",
        industry: "Software",
        postedDays: 6,
        description: "Design and implement enterprise cloud solutions for Fortune 500 clients across industries.",
        badges: [],
        skills: ["AWS", "Azure", "GCP", "Terraform"]
    },
    {
        id: 11,
        title: "Marketing Manager",
        company: "Paytm",
        logo: "Pictures/paytm-logo-png_seeklogo-305549.png",
        location: "Noida, India",
        salary: "₹20-30 LPA",
        experience: "6-10",
        jobType: "Full-time",
        companyType: "Fintech",
        industry: "Marketing",
        postedDays: 3,
        description: "Lead marketing campaigns and brand strategy for Paytm's financial services products.",
        badges: [],
        skills: ["Digital Marketing", "Brand Strategy", "Analytics", "SEO"]
    },
    {
        id: 12,
        title: "Full Stack Developer",
        company: "Razorpay",
        logo: "Pictures/razorpay-logo-png_seeklogo-409477.png",
        location: "Bangalore, India",
        salary: "₹20-32 LPA",
        experience: "3-6",
        jobType: "Full-time",
        companyType: "Fintech",
        industry: "Software",
        postedDays: 2,
        description: "Build payment solutions that power millions of businesses across India.",
        badges: ["Remote"],
        skills: ["React", "Node.js", "PostgreSQL", "Ruby"]
    },
    {
        id: 13,
        title: "HR Manager",
        company: "Wipro",
        logo: "Pictures/wipro-logo-png_seeklogo-328115.png",
        location: "Chennai, India",
        salary: "₹15-22 LPA",
        experience: "6-10",
        jobType: "Full-time",
        companyType: "MNC",
        industry: "Human Resources",
        postedDays: 8,
        description: "Lead HR operations and talent management for our IT services division.",
        badges: [],
        skills: ["Recruitment", "Employee Relations", "HRMS", "Compliance"]
    },
    {
        id: 14,
        title: "Mobile App Developer",
        company: "PhonePe",
        logo: "Pictures/phonepe-logo-png_seeklogo-339867.png",
        location: "Bangalore, India",
        salary: "₹18-28 LPA",
        experience: "1-3",
        jobType: "Full-time",
        companyType: "Fintech",
        industry: "Software",
        postedDays: 1,
        description: "Develop features for India's most loved payments app used by 400M+ users.",
        badges: ["Fast Hiring"],
        skills: ["Flutter", "React Native", "iOS", "Android"]
    },
    {
        id: 15,
        title: "Sales Executive",
        company: "HDFC Bank",
        logo: "Pictures/hdfc-bank-logo-png_seeklogo-184652.png",
        location: "Delhi, India",
        salary: "₹5-8 LPA",
        experience: "0-1",
        jobType: "Full-time",
        companyType: "Banking",
        industry: "Sales",
        postedDays: 10,
        description: "Drive sales of banking products including loans, credit cards, and investment services.",
        badges: ["Fresher"],
        skills: ["Sales", "Communication", "Customer Service", "Banking"]
    },
    {
        id: 16,
        title: "QA Engineer",
        company: "Zoho",
        logo: "Pictures/zoho-corporation-logo-png_seeklogo-506148.png",
        location: "Chennai, India",
        salary: "₹8-14 LPA",
        experience: "1-3",
        jobType: "Full-time",
        companyType: "Product",
        industry: "Software",
        postedDays: 4,
        description: "Ensure quality of our SaaS products through automated and manual testing.",
        badges: [],
        skills: ["Selenium", "Java", "API Testing", "Agile"]
    },
    {
        id: 17,
        title: "Content Writer",
        company: "BYJU'S",
        logo: "Pictures/byjus-logo-png_seeklogo-364776.png",
        location: "Bangalore, India",
        salary: "₹6-10 LPA",
        experience: "1-3",
        jobType: "Hybrid",
        companyType: "Edtech",
        industry: "Creative",
        postedDays: 5,
        description: "Create engaging educational content for K-12 students across multiple subjects.",
        badges: ["Remote"],
        skills: ["Content Writing", "SEO", "Education", "Research"]
    },
    {
        id: 18,
        title: "Supply Chain Manager",
        company: "Reliance",
        logo: "Pictures/reliance-industries-limited-logo-png_seeklogo-200610.png",
        location: "Mumbai, India",
        salary: "₹25-35 LPA",
        experience: "6-10",
        jobType: "Full-time",
        companyType: "Fortune 500",
        industry: "Supply Chain",
        postedDays: 7,
        description: "Optimize supply chain operations for Reliance Retail's nationwide distribution network.",
        badges: [],
        skills: ["Supply Chain", "Logistics", "SAP", "Analytics"]
    },
    {
        id: 19,
        title: "Cybersecurity Analyst",
        company: "Deloitte",
        logo: "Pictures/DELOITEE.png",
        location: "Hyderabad, India",
        salary: "₹12-20 LPA",
        experience: "1-3",
        jobType: "Full-time",
        companyType: "MNC",
        industry: "Software",
        postedDays: 3,
        description: "Protect enterprise systems and conduct security assessments for global clients.",
        badges: [],
        skills: ["Cybersecurity", "SIEM", "Penetration Testing", "Cloud Security"]
    },
    {
        id: 20,
        title: "Technical Lead",
        company: "Meesho",
        logo: "Pictures/meesho-logo-png_seeklogo-507117.png",
        location: "Bangalore, India",
        salary: "₹35-50 LPA",
        experience: "6-10",
        jobType: "Full-time",
        companyType: "Startup",
        industry: "Software",
        postedDays: 2,
        description: "Lead a team of engineers building India's fastest-growing social commerce platform.",
        badges: ["Fast Hiring"],
        skills: ["System Design", "Java", "Leadership", "Microservices"]
    },
    {
        id: 21,
        title: "Financial Analyst",
        company: "CRED",
        logo: "Pictures/cred-logo-png_seeklogo-454844.png",
        location: "Bangalore, India",
        salary: "₹15-25 LPA",
        experience: "3-6",
        jobType: "Full-time",
        companyType: "Fintech",
        industry: "Finance",
        postedDays: 1,
        description: "Analyze financial data and develop models for credit risk assessment.",
        badges: ["Remote"],
        skills: ["Financial Modeling", "Excel", "Python", "SQL"]
    },
    {
        id: 22,
        title: "Operations Manager",
        company: "Ola",
        logo: "Pictures/ola-logo-png_seeklogo-306525.png",
        location: "Mumbai, India",
        salary: "₹18-28 LPA",
        experience: "3-6",
        jobType: "Full-time",
        companyType: "Startup",
        industry: "Operations",
        postedDays: 6,
        description: "Manage city operations and driver partnerships for Ola's ride-sharing platform.",
        badges: [],
        skills: ["Operations", "Team Management", "Analytics", "Problem Solving"]
    },
    {
        id: 23,
        title: "React Developer",
        company: "Groww",
        logo: "Pictures/groww-logo-png_seeklogo-430536.png",
        location: "Bangalore, India",
        salary: "₹15-24 LPA",
        experience: "1-3",
        jobType: "Remote",
        companyType: "Fintech",
        industry: "Software",
        postedDays: 2,
        description: "Build intuitive investment experiences for retail investors across India.",
        badges: ["Remote", "Fast Hiring"],
        skills: ["React", "Redux", "JavaScript", "REST APIs"]
    },
    {
        id: 24,
        title: "Machine Learning Engineer",
        company: "Unacademy",
        logo: "Pictures/unacademy-logo-png_seeklogo-400820.png",
        location: "Bangalore, India",
        salary: "₹22-35 LPA",
        experience: "3-6",
        jobType: "Full-time",
        companyType: "Edtech",
        industry: "Software",
        postedDays: 4,
        description: "Develop ML models to personalize learning experiences for millions of students.",
        badges: [],
        skills: ["Python", "TensorFlow", "NLP", "Deep Learning"]
    },
    {
        id: 25,
        title: "Graphic Designer",
        company: "Nykaa",
        logo: "Pictures/zepto-logo-png_seeklogo-622950.png",
        location: "Mumbai, India",
        salary: "₹8-14 LPA",
        experience: "1-3",
        jobType: "Hybrid",
        companyType: "Startup",
        industry: "Creative",
        postedDays: 8,
        description: "Create stunning visual designs for India's leading beauty and fashion brand.",
        badges: [],
        skills: ["Photoshop", "Illustrator", "Figma", "Branding"]
    }
];

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = jobsData;
}

